apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: opendatahub-operator-

resources:
- ../base

commonAnnotations:
  service.beta.openshift.io/inject-cabundle: "true"

configurations:
- kustomizeconfig.yaml

patches:
-  path: operator-namespace-patch.yaml
  

#patches:
#  - path: remove-namespace-from-webhook.yaml